### PR TITLE
Install python and moodlemlbackend package

### PR DESCRIPTION
**Pull request by dmonllao**

### CODE REVIEW

**Comment by dmonllao** [comment]
This patch should be applied to *jessie branches.

**Comment by andrewnicols** [comment]
Just to mention that the install script here is missing the cleanup side of things.

We must remove apt directories, and python caches too to ensure we don’t have any extra image bloat.

**Comment by dmonllao** [comment]
The patch has been amended to clear apt and pip caches.

**Comment by dmonllao** [comment]
The tensorflow versions required by our python ML backend can't be installed on jessie (Could not find any downloads that satisfy the requirement tensorflow>=1.0.0,<1.1). This is my conclusion after several tries. I've checked that the correct python version is installed, all the required dependencies... I ran out of ideas.

What would you think about discarding this patch and just applying #35 to stretch?

**Comment by dmonllao** [comment]
Ok, closing this issue, thanks.

**Pull request closed without merging**
