### PR TITLE
Add php.ini modification instructions

### PR DESCRIPTION
**Pull request by nadavkav**
Trying to upload a large course backup into the Moodle docker instance, I was limited by php.ini max upload settings.
So I propose adding some instructions about updating php.ini within the running docker

### CODE REVIEW

**Comment by stronk7** [comment]
Uhm... don't this need to restart the service for the changes to make effect?

**Comment by nadavkav** [comment]
You are right @stronk7 , but it was so obvious that I failed to mention it.
Revisiting this, I think the initial max upload size should be much higher then what it is today, to support uploading of large 
 course backups for testing purposes out of the box. (our case)

**Comment by davidscotson** [comment]
Can we add these settings to https://github.com/moodlehq/moodle-php-apache/blob/master/root/usr/local/etc/php/conf.d/docker-php-moodle.ini as I think they're generally helpful.

Might be nice to have instructions for other settings though.

**Comment by stronk7** [comment]
Hi,

I think that now, both with #162 and #167 (both documented in the main readme) it's pretty easy to add any script and/or php configuration.

So I feel that this can be closed now, thanks for your contribution!

If you think that still we should do something else, don't hesitate to open a new issue / PR.

Ciao :-)

**Pull request closed without merging**
